name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for report issue for dominikhajduk/timesheet-style-fixer!"
        pr-message: "Thanks for improving dominikhajduk/timesheet-style-fixer!"
